spring:
  application:
    name: job-platform-api
  profiles:
    active: dev
  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/job_platform # 自行修改数据库名称
    username: root # 自行修改数据库用户名
    password: 123456 # 自行修改数据库密码
  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: false
    clean-disabled: true
    baseline-on-migrate: false # 首次迁移需要设置为true，之后保持false即可
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.sysu.sse.recruitment.job_platform_api.pojo.entity
  type-handlers-package: cn.sysu.sse.recruitment.job_platform_api.server.handler
  mapper-locations: classpath:mapper/*.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

security:
  jwt:
    secret: ${JWT_SECRET:dGhpc19pc19hX3NlY3VyZV9hbmRfbG9uZy1rZXkZm9yX2Rldg}
    expiration-ms: ${JWT_TTL_MS:86400000} # JWT过期时间

file:
  # 管理端图片的访问前缀，例如 http://localhost:8080
  # 在生产环境下应配置为管理端的实际域名
  server-prefix: http://localhost:8081
app:
  storage:
    company-logo-dir: ${COMPANY_LOGO_DIR:uploads/company-logo}
    company-logo-url-prefix: ${COMPANY_LOGO_URL_PREFIX:/files/company-logo}

    student-avatar-dir: ${STUDENT_AVATAR_DIR:uploads/student-avatar}
    student-avatar-url-prefix: ${STUDENT_AVATAR_URL_PREFIX:/files/student-avatar}

    resume-dir: ${RESUME_DIR:uploads/resume}
    resume-url-prefix: ${RESUME_URL_PREFIX:/files/resume}

ai:
  dashscope:
    api-key: sk-69f01499b6c8462ab1d9f93212c04e30
    model: qwen-vl-plus

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    cn.sysu.sse.recruitment.job_platform_api: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
logging:
  level:
    root: INFO
    cn.sysu.sse.recruitment.job_platform_api: INFO

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: INFO
    cn.sysu.sse.recruitment.job_platform_api: INFO